name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Cache references
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install dependencies
      run: |
        git submodule update --init --recursive && make clean
    - name: Build figures
      run: make all
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: |
          output/*.svg
          spell.txt
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: github.ref == 'refs/heads/master'
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: output # The folder the action should deploy.
        SINGLE_COMMIT: true
